<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

  <PropertyGroup>
    <HotChocolateImplicitUsings>disable</HotChocolateImplicitUsings>
    <Nullable>annotations</Nullable>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>
</Project>
